name: Manually triggered Matrix Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_v: [6, 8, 12]
        include:
          - os: ubuntu-latest
            node_v: 8
            is_ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node_v: 6
          - os: macos-latest
            node_v: 8

    runs-on: ${{ matrix.os }}
    env:
      IS_UNUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_v }}
      - name: Log node version
        run: |
          node -v
          echo $IS_UNUNTU_8