name: Hello World

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true
jobs:
  hello-world-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Checking Version of gcc
        run: gcc --version
      - name: Checking version of g++
        run: g++ --version
      - name: Set up GCC
        uses: actions/checkout@v1
      - name: compiling c code
        run: gcc ./hello-world.c -o hello-world.out
      - name: Listing all file in the current directory
        run: ls -l
      - name: Running comipled code
        run: ./hello-world.out
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo we can run many command
