name: Hello World

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true
jobs:
  hello-world-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Checking Version of gcc & g++
        run: |
          gcc --version
          g++ --version
      - name: Set up GCC
        uses: actions/checkout@v1
      - name: compiling and running c code
        run: |
          gcc ./hello-world.c -o hello-world.out
          ls -l
          ./hello-world.out
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo we can run many command
      - name: Compile and run c++ code
        run: |
          g++ ./sort-data.cpp -o sort-data.out
          ./sort-data.out 
          python --version
      - name: running python code
        run: |
          python ./sorted.py
          java -version
          java --version
      - name: Running Java Program
        run: |
          javac HelloWorld.java
          java HelloWorld